spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/school?characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver

    mybatis-plus:
      mybatis-plus:
        type-aliases-package: com.mybatisplus.entity
      mapper-locations: classpath:mapper/*.xml
      global-config:
        field-strategy: 2
        db-column-underline: true
        refresh-mapper: true
        sql-parser-cache: false
      configuration:
        map-underscore-to-camel-case: true
        call-setters-on-nulls: true
        cache-enabled: false


logging:
  level:
    root: INFO
    ysw.mybatisplus.mapper*: debug
